server:
  port: 30102

spring:
  application:
    name: engine

mq:
  proxy: 192.168.5.182:8081
  enable-ssl: false
  producer:
    topics:
      - "client_topic_A"
      - "client_topic_B"
    init-num: 2
    max-attempts: 3
  consumers:
    client-group-one:
      type: simple
      topic-tags:
        - "client_topic_A:tagA:tagB"
        - "client_topic_B:tagA:tagB"
      thread-num: 3
      init-num: 2
    client-group-two:
      type: push
      topic-tags:
        - "client_topic_A:tagC:tagD"
        - "client_topic_B:tagC:tagD"
      thread-num: 3
      listener: com.game.log.engine.consumer.push.ClientGroupTwoMessageListener


