server:
  port: 30102

spring:
  application:
    name: engine

mq:
  proxy: 192.168.5.182:8081
  enable-ssl: false
  producer:
    topics:
      log_comment_topic:
        is_trans: false
      log_transaction_topic:
        is_trans: true
    checker: com.game.log.engine.MyTransactionChecker
    #最大内部重试次数
    max-attempts: 3
  consumers:
    # 消费者组名称
    simple_consumers_group_one:
      # 消费者类型 simple\push\pull
      type: simple
      # 监听topic和tags
      topic-tags:
        - "client_topic_A:tagA:tagB"
        - "client_topic_B:tagA:tagB"
    push_consumers_group_one:
      # 消费者类型 simple\push\pull
      type: push
      # 监听topic和tags
      topic-tags:
        - "client_topic_A:tagC:tagD"
        - "client_topic_B:tagC:tagD"
      # 消息消费的线程组数量，即消费者组消费者数量（只用于push类型的消费者组）
      thread-num: 3
      # 指定消息监听处理类 （只用于push类型的消费者组）
      listener: com.game.log.engine.consumer.push.ClientGroupTwoMessageListener


