server:
  port: 30102

spring:
  application:
    name: engine

mq:
  nameserver: 192.168.5.182:9876
  enable-ssl: false
  producer:
    topics:
      - "client-topic-A"
      - "client-topic-B"
    init-num: 2
    max-attempts: 3
  consumers:
    client-group-one:
      type: simple
      topic-tags:
        - "client-topic-A:tagA:tagB"
        - "client-topic-B:tagA:tagB"
      thread-num: 3
      init-num: 2
    client-group-two:
      type: push
      topic-tags:
        - "client-topic-A:tagC:tagD"
        - "client-topic-B:tagC:tagD"
      thread-num: 3
      listener: com.game.log.engine.consumer.listener.ClientGroupTwoMessageListener


