server:
  port: 30102

spring:
  application:
    name: engine


rocketmq:
  name-server: 192.168.5.182:9876
  producer:
    send-message-timeout: 10000
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
    # 1024 * 1024 * 4  = 4M
#    max-message-size: 4194304
#    compress-message-body-threshold: 4096
    retry-next-server: false
    group: comment_producer_group
  pull-consumer:
    pull-batch-size: 20
    message-model: "CLUSTERING"
    group: comment_consumer_group


mq:
  topic:
    comment: comment_topic
    transaction: transaction_topic
    retry: retry_topic
  consumer:
    comment:
      group: comment_consumer_group
    transaction:
      group: transaction_consumer_group
    retry:
      group: retry_topic_group


