server:
  port: 30102

spring:
  application:
    name: engine

mq:
  nameserver: 192.168.5.182:9872
  enable-ssl: false
  producer:
    topics:
      - "client-topic-A"
      - "client-topic-B"
    init-num: 2
    max-attempts: 3
  consumers:
    one-consumer:
      topic-tags:
        - "client-topic-A:tagA:tagB"
        - "client-topic-B:tagA:tagB"
      thread-num: 3
      group: "client-group"
    two-consumer:
      topic-tags:
        - "client-topic-A:tagC:tagD"
        - "client-topic-B:tagC:tagD"
      thread-num: 3
      group: "client-group"


